# @format
services:
  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: elsquaz/biblestudyai-backend:latest
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@timescale:${POSTGRES_PORT}/${POSTGRES_DB}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:${REDIS_PORT}
      - KAFKA_BOOTSTRAP_SERVERS=rpk:9092
      - DEEPHAVEN_SERVER=http://deephaven:10000
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
    depends_on:
      timescale:
        condition: service_healthy
      redis:
        condition: service_healthy
      rpk:
        condition: service_started
      deephaven:
        condition: service_started
      milvus:
        condition: service_started
      neo4j:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./db:/app/db
    env_file:
      - .env
    networks:
      - biblestudyai-network
    restart: unless-stopped

  # React Frontend (Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: elsquaz/biblestudyai-frontend:latest
    container_name: react-frontend
    command: ["npm", "run", "dev"]
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=http://backend:8000
      - VITE_WS_URL=ws://backend:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - biblestudyai-network

  # TimescaleDB with pgvectorscale
  timescale:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - biblestudyai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Redis Stack (includes RedisJSON, RedisSearch, RedisTimeSeries)
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
      - "8001:8001" # RedisInsight
    volumes:
      - redis_data:/data
    networks:
      - biblestudyai-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Deephaven Server
  deephaven:
    image: ghcr.io/deephaven/server:latest
    container_name: deephaven
    ports:
      - "10000:10000"
    environment:
      - START_OPTS=-Xmx4g -DAuthHandlers=io.deephaven.auth.AnonymousAuthenticationHandler
    networks:
      - biblestudyai-network

  # Redpanda Kafka
  rpk:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
    ports:
      - "9092:9092"
      - "8082:8082"
      - "8081:8081"
      - "9644:9644"
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    networks:
      - biblestudyai-network

  # Milvus Vector Database
  milvus:
    image: milvusdb/milvus:latest
    container_name: milvus
    command: ["milvus", "run", "standalone"]
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
    ports:
      - "19530:19530"
    volumes:
      - milvus_data:/var/lib/milvus/data
    depends_on:
      - etcd
      - minio
    networks:
      - biblestudyai-network

  # MinIO for Milvus
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: minio server /minio_data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    networks:
      - biblestudyai-network

  # etcd for Milvus
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    volumes:
      - etcd_data:/etcd
    networks:
      - biblestudyai-network

  # Neo4j Graph Database
  neo4j:
    image: neo4j:5
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use_neo4j_config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - biblestudyai-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:7474",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  timescaledb_data: {}
  redis_data: {}
  redpanda_data: {}
  milvus_data: {}
  etcd_data: {}
  minio_data: {}
  neo4j_data: {}

networks:
  biblestudyai-network:
    driver: bridge
